#
# problemset.yaml - list of CCS problem definitions
#
# created on: Mon Dec 23 08:50:29 PST 2019
# created by: $Id: mkprobset,v 1.8 2017/04/29 00:19:22 laned Exp $
#
problems:
  - letter:     A
    short-name: a
    clics-id : 'A-problem'
    color:      Dark green
    rgb:        '#399956'

  - letter:     B
    short-name: b
    clics-id : 'B-problem'
    color:      Purple
    rgb:        '#825eaa'

  - letter:     C
    short-name: c
    clics-id : 'C-problem'
    color:      Red
    rgb:        '#df1328'

